name: openisr
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - loguru
  - fastapi
  - uvicorn-standard
  - python-multipart
  - sqlalchemy
  - alembic
  - pillow
  - pip:
      - opencv-contrib-python-headless
