version: "3.8"
services:
  openisr-advanced:
    image: lovindata/openisr:latest
    ports:
      - "5000:5000"
    environment:
      - OPENISR_API_PORT=5000
      - OPENISR_PROCESS_TIMEOUT_IN_SECONDS=30
    volumes:
      - ./data:/app/backend/data